- ['res.partner', 'image', 'image_1920', 'Search for Commit']
- ['res.users', 'image', 'image_1920', 'Search for Commit']
- ['image.mixin', 'image', 'image_1920', 'Search for Commit']
- ['mail.channel', 'image', 'image_128', 'Search for Commit']
